
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX

    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0fch ; XXXXXX..
    db 0f8h ; XXXXX...
    db 0f0h ; XXXX....
    db 0f0h ; XXXX....

    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 03fh ; ..XXXXXX
    db 01fh ; ...XXXXX
    db 00fh ; ....XXXX
    db 01fh ; ...XXXXX

    db 0f0h ; XXXX....
    db 0f0h ; XXXX....
    db 0f8h ; XXXXX...
    db 0fch ; XXXXXX..
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX

    db 00fh ; ....XXXX
    db 00fh ; ....XXXX
    db 01fh ; ...XXXXX
    db 03fh ; ..XXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX
    db 0ffh ; XXXXXXXX

    db 0f0h ; XXXX....
    db 0f0h ; XXXX....
    db 0f8h ; XXXXX...
    db 0fch ; XXXXXX..
    db 03fh ; ..XXXXXX
    db 01fh ; ...XXXXX
    db 00fh ; ....XXXX
    db 00fh ; ....XXXX

    db 00fh ; ....XXXX
    db 00fh ; ....XXXX
    db 01fh ; ...XXXXX
    db 03fh ; ..XXXXXX
    db 0fch ; XXXXXX..
    db 0f8h ; XXXXX...
    db 0f0h ; XXXX....
    db 0f0h ; XXXX....

    db 000h ; ........
    db 000h ; ........
    db 000h ; ........
    db 000h ; ........
    db 000h ; ........
    db 000h ; ........
    db 000h ; ........
    db 000h ; ........

